integration:
  services:
    account-service:
      base-url: http://localhost:9001
      timeout: 3000
    customer-service:
      base-url: http://localhost:9002
      timeout: 3000
    pricing-service:
      base-url: http://localhost:9003
      timeout: 3000

spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6380  # Different port for test Redis

cache:
  enabled: false  # Disable cache for testing

logging:
  level:
    root: INFO
    io.swagger: DEBUG
